# Generated by Django 5.0.6 on 2024-05-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentartpiece',
            name='sent_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
