# Generated by Django 5.0.6 on 2024-06-04 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sentartpiece_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentartpiece',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='sentartpiece',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
