# Generated by Django 5.0.6 on 2024-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permission set for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
