# Generated by Django 5.0.6 on 2025-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='Jonathan Heaney loved a piece of art you shared!'),
            preserve_default=False,
        ),
    ]
