# Generated by Django 5.0.6 on 2025-08-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_on_art_shared',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_on_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_on_like',
            field=models.BooleanField(default=False),
        ),
    ]
