# Generated by Django 5.0.6 on 2025-08-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_customuser_email_on_art_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_art_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='receive_art_paused',
            field=models.BooleanField(default=False),
        ),
    ]
