# Generated by Django 5.0.6 on 2025-08-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_customuser_last_art_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentartpiece',
            name='source',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('welcome', 'Welcome'), ('reciprocal', 'Reciprocal'), ('manual', 'Manual')], default='weekly', max_length=20),
        ),
    ]
