# Generated by Django 5.0.6 on 2025-08-21 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_reciprocalgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciprocalgrant',
            name='sent_art_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciprocal_granted_to', to='main.artpiece'),
        ),
    ]
