# Generated by Django 5.0.6 on 2025-08-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_reciprocalgrant_sent_art_piece'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='welcome_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='welcome_weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
