# Generated by Django 5.0.6 on 2025-08-21 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_artpiece_welcome_eligible_artpiece_welcome_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_art_piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_granted_to', to='main.artpiece')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='main_welcom_created_b58b2a_idx')],
            },
        ),
    ]
