# Generated by Django 5.0.6 on 2025-08-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_add_public_id_to_artpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentartpiece',
            name='seen_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
