# Generated by Django 5.0.6 on 2025-08-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sentartpiece_seen_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(condition=models.Q(('parent_comment__isnull', True)), fields=('art_piece', 'sender', 'recipient'), name='uniq_comment_top_thread_piece_sender_recipient'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.Index(fields=['art_piece', 'sender', 'recipient'], name='idx_comment_piece_sender_recipient'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.Index(fields=['art_piece', 'created_at'], name='idx_comment_piece_created'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.Index(fields=['parent_comment'], name='idx_comment_parent'),
        ),
    ]
