# Generated by Django 5.0.6 on 2025-08-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_comment_uniq_comment_top_thread_piece_sender_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='idx_comment_piece_sender_recipient',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='idx_comment_piece_created',
        ),
        migrations.RemoveConstraint(
            model_name='comment',
            name='idx_comment_parent',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['art_piece', 'sender', 'recipient'], name='idx_comment_piece_sender_recip'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['art_piece', 'created_at'], name='idx_comment_piece_created'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment'], name='idx_comment_parent'),
        ),
    ]
