# Generated by Django 5.0.6 on 2025-09-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_comment_idx_comment_piece_sender_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
