# Generated by Django 5.0.6 on 2025-09-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_customuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
