# Generated by Django 5.0.6 on 2025-09-07 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_cleanup_user_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='delete_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_artpieces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
