# Generated by Django 5.0.6 on 2025-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='receive_blog_emails',
            field=models.BooleanField(default=True),
        ),
    ]
